server:
  port: 7001
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔( default:30s )
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5s的时间间隔( default: 90 s )
    hostname: 127.0.0.1
  client:
    register-with-eureka: false   #是否将自己注册到eureka中
    fetch-registry: false         #是否从eureka中获取信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false   #设置为false表示关闭保护模式.在保护模式下，如因为网络或其它问题服务提供者掉线的话，eureka不会立即清空服务列表
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，ms (默认是60秒）
spring:
  application:
    name: eureka